name = "FirePortal SMP"
author = "mcree"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95eb92089a4049b22f773036dd24d5b89624166428a8ab73ce4b6ded6955c6d1"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
